### ISSUE TITLE
Validate rewire arguments?

### ISSUE THREAD

**Issue by andriijas** [timarney/react-app-rewired#130]
The documentation says rewires should be wrapped with extra function if allowing extra options, like this:

```
function createRewire(options = {}) {
 return function (config, env) {}
}
```

A lot of community rewires adds options add third argument instead:
```
function (config, env, options = {}) {}
```

https://github.com/lwd-technology/react-app-rewire-define-plugin/blob/master/index.js
https://github.com/osdevisnot/react-app-rewire-contrib/blob/master/packages/react-app-rewire-emotion/index.js

Is there any way to validate so that community plugins comply to the new compose API?

**Comment by likun7981** [comment]
There are two ways to add additional parameters.
For the `required` param, the `rewire` should be wrapped with extra function, if the params is `optional`,  You can refer to `react-app-rewire-less`.

In fact `compose` is just a tool to reduce duplicate code, like this
```javascript
config = reiwireSomeA(config, env)
config = reiwireSomeB(config, env)
config = reiwireSomeC(config, env)
```
If you can not use `compose`, it also can work fine for `react-app-rewired`, so the plugin param is not comply the `compose`, you can use it without `compose`. 
We can not verify their parameters because we can not control the process of rewriting `config`

**Comment by andriijas** [comment]
👍
