### ISSUE TITLE
Cannot read property 'exclude' of undefined

### ISSUE THREAD

**Issue by zhaoyu69** [timarney/react-app-rewired#145]
use ant-design in create-react-app，err in react-app-rewire-less，details that the flowing items show.

1.package.json 

![package](https://user-images.githubusercontent.com/23548734/33252013-4ed5a13e-d376-11e7-8c2c-91e5a5cc0018.png)

2.config-override

![config-override](https://user-images.githubusercontent.com/23548734/33252148-5db3f27c-d377-11e7-914b-06f81297977c.png)

3.npm start err

![exclude](https://user-images.githubusercontent.com/23548734/33252157-669af5ac-d377-11e7-8a8b-ec8ac7a1e2fc.png)

4.delete some code related to less，it works but...no style！

![deleteitem](https://user-images.githubusercontent.com/23548734/33252161-6d3e75dc-d377-11e7-90b6-a78d92e3f70e.png)

![nocss](https://user-images.githubusercontent.com/23548734/33252169-76229c82-d377-11e7-8f54-83df82040668.png)

5.update config-override.js type：true ===> type：'css'，it works for css but not for less.

![noless](https://user-images.githubusercontent.com/23548734/33252175-7b664298-d377-11e7-9633-144473b3b341.png)

how to resolve it to make my project works well ?

**Comment by likun7981** [comment]
You can see [here](https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewire-less/README.md#add-it-to-your-project), a change for `react-app-rewire-less`

**Comment by zhaoyu69** [comment]
[https://github.com/zhaoyu69/antd-spa](https://github.com/zhaoyu69/antd-spa) 
This is my github address. 
It contains serialport, so you have to config 
from [https://github.com/nodejs/node-gyp](https://github.com/nodejs/node-gyp).

Thanks！

**Comment by zhaoyu69** [comment]
Or you can commented out some part of component.
I just want to see the less style to work.

**Comment by likun7981** [comment]
I test your demo code and add `rewire-less` with options,  it is not wrong.

**Comment by zhaoyu69** [comment]
I try again with another PC , also not work. can you give me some advice?

**Comment by dawnmist** [comment]
I've also just tried your git repo (master). Before I could test, I made the following changes:
1. Upgraded react-app-rewire-less to 2.1.0 first - the repo is pointing to ^2.0.9 in the package-lock.json file rather than the ^2.1.0 in your report.
2. Added the less rewire back into the config-overrides.js file.
3. Fixed the case of the less filename imported in the acq1 component - I'm on linux, so paths are case-sensitive. The ACQ1.jsx file was importing the acq1.less file in upper-case while the filename for the less file was lower-case.

Having made those 3 changes to the master version of your repository, both `yarn start` and 'npm run start' were able to run the app and show the ![login screen](https://user-images.githubusercontent.com/5810277/33325574-c5da3b2e-d4a6-11e7-9f82-d6a401eb5366.png).

**Comment by likun7981** [comment]
The path separators is use `path.sep` , This can not be a  path separators question.  you can clear your `npm cache` and delete `package-lock.json`, try again install.

**Comment by dawnmist** [comment]
I saw that we were using `path.sep` - what I wasn't sure about was whether the `require.resolve('file-loader')` that react-scripts use returns the path in Windows or Posix format when used on a Windows system. Since the actual failure line points to the line where we try to alter the file-loader rule, it stands to reason that there is something odd causing it to be unable to find that rule on some computers. Since the example repo also had an issue where it was importing a local file with the wrong case ('ACQ1.less' instead of 'acq1.less'), it indicated that @zhaoyu69 was possibly working on an OS where filenames were not case-sensitive. Hence my question about using Windows and why I was suspicious that there might have been a mismatch between the file-loader definition from react-scripts and our searching for it using path.sep.

**Comment by zhaoyu69** [comment]
I Follow your steps，try again but failed too，I'm going to redo my system then try again.

**Comment by dawnmist** [comment]
@zhaoyu69 If it is still failing after redoing your system, could you please alter your config-overrides.js file to add the following 4 lines after the call to injectBabelPlugin to get some logging output then post the output:
```
module.exports = function override(config, env) {
    config = injectBabelPlugin(['import', { libraryName: 'antd', style: true }], config);
    RegExp.prototype.toJSON = function() { return this.toString() }
    console.log(`Rules: ${JSON.stringify(config.module.rules)}`);
    console.log(`PathSep: ${path.sep}`);
    throw new Error('Escape here...');
```
Note: This will *not* fix anything, its purpose is to generate some debugging information so that we can try to see what the react-app-rewire-less plugin is being given as input. The `throw new Error` just makes sure that the script doesn't continue any further. All 4 new lines _should be removed again_ after generating the logging text.

**Comment by zhaoyu69** [comment]
I added a word : const { path } = require('path');
but throw error : TypeError: Cannot read property 'sep' of undefined
How to deal with it?

**Comment by dawnmist** [comment]
Sorry - I forgot that bit.

Use `const path = require('path')` - no braces.

**Comment by zhaoyu69** [comment]
Rules: [
  {
    "test": "/\\.(js|jsx)$/",
    "enforce": "pre",
    "use": [
      {
        "options": {
          "eslintPath": "E:\\WEB\\projects\\antd-spa\\node_modules\\_eslint@4.4.1@eslint\\lib\\api.js",
          "baseConfig": {
            "extends": [
              "E:\\WEB\\projects\\antd-spa\\node_modules\\_eslint-config-react-app@2.0.1@eslint-config-react-app\\index.js"
            ]
          },
          "ignore": false,
          "useEslintrc": false
        },
        "loader": "E:\\WEB\\projects\\antd-spa\\node_modules\\_eslint-loader@1.9.0@eslint-loader\\index.js"
      }
    ],
    "include": "E:\\WEB\\projects\\antd-spa\\src"
  },
  {
    "oneOf": [
      {
        "test": [
          "/\\.bmp$/",
          "/\\.gif$/",
          "/\\.jpe?g$/",
          "/\\.png$/"
        ],
        "loader": "E:\\WEB\\projects\\antd-spa\\node_modules\\_url-loader@0.5.9@url-loader\\index.js",
        "options": {
          "limit": 10000,
          "name": "static/media/[name].[hash:8].[ext]"
        }
      },
      {
        "test": "/\\.(js|jsx)$/",
        "include": "E:\\WEB\\projects\\antd-spa\\src",
        "loader": "E:\\WEB\\projects\\antd-spa\\node_modules\\_babel-loader@7.1.1@babel-loader\\lib\\index.js",
        "options": {
          "babelrc": false,
          "presets": [
            "E:\\WEB\\projects\\antd-spa\\node_modules\\_babel-preset-react-app@3.1.0@babel-preset-react-app\\index.js"
          ],
          "cacheDirectory": true,
          "plugins": [
            [
              "import",
              {
                "libraryName": "antd",
                "style": true
              }
            ]
          ]
        }
      },
      {
        "test": "/\\.css$/",
        "use": [
          "E:\\WEB\\projects\\antd-spa\\node_modules\\_style-loader@0.18.2@style-loader\\index.js",
          {
            "loader": "E:\\WEB\\projects\\antd-spa\\node_modules\\_css-loader@0.28.4@css-loader\\index.js",
            "options": {
              "importLoaders": 1
            }
          },
          {
            "loader": "E:\\WEB\\projects\\antd-spa\\node_modules\\_postcss-loader@2.0.6@postcss-loader\\lib\\index.js",
            "options": {
              "ident": "postcss"
            }
          }
        ]
      },
      {
        "exclude": [
          "/\\.js$/",
          "/\\.html$/",
          "/\\.json$/"
        ],
        "loader": "E:\\WEB\\projects\\antd-spa\\node_modules\\_file-loader@0.11.2@file-loader\\index.js",
        "options": {
          "name": "static/media/[name].[hash:8].[ext]"
        }
      }
    ]
  }
]
PathSep: \

**Comment by dawnmist** [comment]
Thank you for that - it shows why the search for the file-loader is failing.

On your system, searching for a `loader` variable that contains `\file-loader\`. The actual file-loader loader variable contains `@file-loader\` instead.

In node_modules/react-app-rewire-less/index, can you change lines 8-14 so that they are:
```
    const fileLoader = getLoader(
      config.module.rules,
      rule =>
        rule.loader &&
        typeof rule.loader === 'string' &&
        (rule.loader.indexOf(`${path.sep}file-loader${path.sep}`) !== -1 ||
        rule.loader.indexOf(`@file-loader${path.sep}`) !== -1)
    );
```
and give that a test?

**Comment by zhaoyu69** [comment]
Thank you！ It run perfectly.
But if i git this profile and npm install to run next time，
I also need to modify this file?
I need to configure what to change this situation ？

**Comment by dawnmist** [comment]
Temporarily, yes, it will need to be modified manually.

I am working to get a pull request accepted to fix this permanently - once that is completed, the following release should no longer need to be patched manually.

**Comment by zhaoyu69** [comment]
Ok, thank you so much.
