### ISSUE TITLE
Directly call start script

### ISSUE THREAD

**Issue by danwoodbury** [timarney/react-app-rewired#205]
Hi,

Great project. Although I have one question, is there a way to call the start script directly for usage with node process managers such as PM2? We have multiple react apps that integrate with each other so we use PM2 to manage this process and can currently call `node_modules/react-scripts-ts/scripts/start.js` within PM2 to launch the app. 

Is there a way to do this using rewired?

Thanks

**Comment by dawnmist** [comment]
The normal react-app-rewired script is https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/bin/index.js

Looking at this, it doesn't appear to be doing anything special other than to spawn the requested script, so I believe that you could call `node_modules/react-app-rewired/scripts/start.js` directly in the same way that you currently call the react-scripts-ts start script.

Since you're using react-scripts-ts, remember to use the `--scripts-version` parameter when calling the react-app-rewired script. i.e. `node_modules/react-app-rewired/scripts/start.js --scripts-version react-scripts-ts`.

**Comment by danwoodbury** [comment]
legend. Thanks for that. Works a charm after figuring out the PM2 api!
