### ISSUE TITLE
 Error only in the build

### ISSUE THREAD

**Issue by jeiker26** [timarney/react-app-rewired#224]
Hello everyone,

I have this config in my project for css-modules (config-overrides.js):
```
const { getLoader } = require("react-app-rewired");

const cssLoaderMatcher = rule => {
  return rule.loader && rule.loader.indexOf("css-loader") !== -1;
};

const rewireCSS = config => {
  const cssRules = getLoader(
    config.module.rules,
    rule => rule.test && String(rule.test) === String(/\.css$/)
  );

  cssRules.test = /\.s?css$/;
  const cssLoader = getLoader(config.module.rules, cssLoaderMatcher);

  if (cssLoader) {
    cssLoader.options = {
      modules: true,
      importLoaders: 1,
      localIdentName: "[local]___[hash:base64:5]"
    };
  }
  return config;
};

module.exports = rewireCSS;
```

It works perfectly in test and development, but when generating the Build it gives an error: cssLoader undefined.

Thank you very much.

**Comment by dawnmist** [comment]
Create-react-app puts the loader inside the 'use' field when doing a production build instead of inside the 'loader' field that it would normally be in for dev mode.
https://github.com/facebook/create-react-app/blob/836bb39394bef9d83d4dd0cccea08c156dbf298f/packages/react-scripts/config/webpack.config.prod.js#L257-L288

Try changing your css rules search to the following (it's what I'm using for create-react-app-typescript, but that part of the webpack configs appear to be the same so I believe it'll work with create-react-app too):
```javascript
const { getLoader, loaderNameMatches } = require('react-app-rewired');

const cssLoaderMatcher = rule => loaderNameMatches(rule, 'css-loader'));

const rewireCSS = config => {
  const cssRules = getLoader(
    config.module.rules,
    rule => rule.test && String(rule.test) === String(/\.css$/)
  );

  cssRules.test = /\.s?css$/;
  const cssLoader = getLoader(cssRules.use || cssRules.loader, cssLoaderMatcher);
```

**Comment by jeiker26** [comment]
Hello,

Thank you very much for everything, the solution that you have passed to me works perfectly.
