### ISSUE TITLE
react-app-rewire-less doesn't works

### ISSUE THREAD

**Issue by NugzarGaguliya** [timarney/react-app-rewired#234]
[reproducing repository](https://github.com/NugzarGaguliya/react-architecture)

I have added this code to my config-overrides.js
```javascript
const rewireLess = require('react-app-rewire-less');

module.exports = function override(config, env) {

 config = rewireLess(config, env);

  return config;
};
```
but build says that 
```Module not found: Can't resolve 'test.less' in 'C:\projects\react-architecture\src\core'```

**Comment by NugzarGaguliya** [comment]
I don't understand, does my repo works on your machine? You are not getting error?

**Comment by vadistic** [comment]
Yes it works - you just need to correct import in `'C:\projects\react-architecture\src\core'`. Write `import './test.less` instead of `import 'test.less` so webpack/typescript won't be searching for `test.less` in node_modules.

The rest of other stuff I wrote is just a hack to reuse same less variables sheet between your styling and variable overrides for ant design - without it you would have to keep two theme variable sheets: one in CSS Object Style for modifyVars and second in .less for your less styling. Sorry for any confusion :)

**Comment by NugzarGaguliya** [comment]
Thank you. It's stupid bug, and I knew about it.
