### ISSUE TITLE
Incorrect behaviour when using Jest's Array type config (collectCoverageFrom)

### ISSUE THREAD

**Issue by hardyscc** [timarney/react-app-rewired#240]
I don't know whether this is the expected behaviour or not, however i just report this in case someone face the same problem..

in my package.json
```
  "jest": {
    "collectCoverageFrom": [
      "src/components/**/*.{js,jsx}"
    ]
  }
```

after apply react-app-rewired,  the collectCoverageFrom become `[ 'src/components/**/*.{js,jsx}', 'src/**/*.{js,jsx,mjs}' ]`, which is not the default behaviour of react-scripts, as it won't include the jest default `'src/**/*.{js,jsx,mjs}'` .

**Comment by dawnmist** [comment]
This has occurred due to a combination of two things.

First - most jest configuration options are not permitted by react-scripts. How react-app-rewired works around this is it takes a copy of all your defined jest options from package.json, and then passes into react-scripts everything _except_ your jest options (i.e. it deletes the jest options part). This means that react-scripts isn't seeing the overrides for even the few fields it does permit overrides for.

React-app-rewired then _merges_ any array or object values defined in package.json with the original values from react-scripts instead of overwriting them. I don't know the history of why it was done this way rather than overriding them.

What you can do to make an override setting instead of a setting to be merged is to apply the setting inside the jest function in config-overrides, which is run _after_ the merge has occurred. This lets you make a full replacement instead of a merge replacement.

```javascript
module.exports = {
  jest: (config) => {
    config.collectCoverageFrom = ["src/components/**/*.{js,jsx}"];
    return config;
  }
}
```

**Comment by hardyscc** [comment]
Thank you very much, IMO the purpose of react-app-rewired is to modified the unsupported config temporary, once react-scripts supported then can remove it.. so I think it shouldn't break the default behaviour of any untouched config unless it has a bigger reason.

**Comment by Gidgidonihah** [comment]
The response to fix it in config-overrides.js is super helpful. Thanks, I wasted a LOT of time trying to figured out why this wasn't working the node_modules.

However, I would argue that this issue shouldn't be closed. Either revisiting the decision to merge, or at the very least comments in the readme about it.

I've opened #294 to add comments to the readme, but currently the travis builds are failing.

**Comment by akuji1993** [comment]
Anyone has tried this in the last few weeks? collectCoverageFrom doesn't seem to be impacted by this fix, as it still shows it tested ALL qualifying files with the correct ending, even though they are not located in a folder that is included in the array.

**Comment by akuji1993** [comment]
Found another solution, for this specific command, you can just add it to your cli command in package.json like so 
`"react-app-rewired test --env=jsdom --collectCoverageFrom=src/components/**/*.{ts,tsx}"`
