### ISSUE TITLE
react-app-rewire-scss not in Community Maintained Rewires.

### ISSUE THREAD

**Issue by johnunclesam** [timarney/react-app-rewired#271]
If I go here: https://github.com/timarney/react-app-rewired/tree/master/packages

I can see this: https://github.com/timarney/react-app-rewired/tree/master/packages/react-app-rewire-sass

but it says: `This package has been deprecated and moved to react-app-rewire-scss`.

But it doesn't show in **Community Maintained Rewires** in Readme. **Why**?

**It's easier to use** than facebook's solution (https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc)?

**Comment by aze3ma** [comment]
@johnunclesam check #267

**Comment by johnunclesam** [comment]
Ok, but this is the same of facebook's solution (https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc) and it's easier to use than facebook's one?

**Comment by aze3ma** [comment]
@johnunclesam it's different from CRA solution because CRA just provide you a way to watch a compile sass files on the fly so you finally ```import './App.css'``` for example instead our solution which is provide a functionality to rewiring the webpack configuration of CRA without need to eject it and also in a much cleaner way so you don't need to write diffrent scripts in your ```package.json``` to watch files with ```node-sass-chockidar```  and also you will not have a duplicate style files inside your src directory.

**Comment by johnunclesam** [comment]
Amazing. Thanks.
