### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by puppylover369** [timarney/react-app-rewired#295]
I'm trying to use Relay with create-react-app, and it's proving to be pretty difficult.  I decided to try react-app-rewired to see if that would help run the relay plugin (keep in mind, I'm not very familiar with how create-react-app works) but I get the following error:

```
/home/priya/Documents/code/ETFication/etfication_web/config-overrides.js:3
  config.module.loaders[0].query.plugins =  ['relay'];
                       ^

TypeError: Cannot read property '0' of undefined
    at Object.override [as webpack] (/home/priya/Documents/code/ETFication/etfication_web/config-overrides.js:3:24)
    at Object.<anonymous> (/home/priya/Documents/code/ETFication/etfication_web/node_modules/react-app-rewired/scripts/start.js:13:13)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

**Comment by timarney** [comment]
Not sure if this will work as I don't use relay but there's a rewire you can pull in here's the code inside it.
https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewire-relay/index.js

**Comment by puppylover369** [comment]
I decided to just replace my config-overrides file with the react-app-rewire-relay code, but it still can't seem to find config.module.loaders

**Comment by dawnmist** [comment]
Try `config.module.rules` - the rules for loaders are usually in that (at least, they are for Webpack 2 & Webpack 3 - I haven't checked for 4).

**Comment by puppylover369** [comment]
Do I have access to that file if I'm using create-react-app?

**Comment by dawnmist** [comment]
The `config` value passed into your config-overrides.js function is the webpack config that will be used when building or starting the dev server. I believe that the reason you can't find `config.module.loaders` is because that is the _wrong_ name for the variable - it's now called "rules", not "loaders". The name changed between Webpack 1 and Webpack 2 - https://stackoverflow.com/questions/43002099/rules-vs-loaders-in-webpack-whats-the-difference .

The other thing from what little you've said that may continue to be a problem is the relay instructions you're trying to use seem to be old/out of date.

What set of instructions are you trying to follow?

If I'm reading the [relay site](https://facebook.github.io/relay/docs/en/installation-and-setup.html) correctly, all you need is to add the relay plugin to the babel loader, right? If so, the following should do the job:
```javascript
const { injectBabelPlugin } = require('react-app-rewired');

module.exports = function override(config, env) {
  config = injectBabelPlugin('relay', config);
  return config;
}
```

**Comment by puppylover369** [comment]
Thanks, that seemed to have worked (though there are some other errors I have to work through before I can figure out whether it actually worked).  Since it would help me understand, what exactly does the "override" function do?

**Comment by timarney** [comment]
override takes in the original CRA webpack config as a parameter.
At which point you can modify it as need be and than return it back.

**Comment by puppylover369** [comment]
Thanks all
