### ISSUE TITLE
Make graphql-persisted-document-loader work with react-app-rewired

### ISSUE THREAD

**Issue by frederikhors** [timarney/react-app-rewired#312]
I'm newbie.

Is there a way to make this package (https://github.com/leoasis/graphql-persisted-document-loader) work with react-app-rewired?

How to do?

**Comment by dawnmist** [comment]
Looking at the instructions on that page, it looks like you should be able to do this:
```javascript
// Reusable JSON.stringify replacer function that turns RegExp values into strings for
// debugging (Otherwise a RegExp is output as "{}" - this outputs it as "/*.jsx?/")
const stringifyConfig = (key, value) => {
  if (value instanceof RegExp) {
    return value.toString();
  }
  return value;
};

module.exports = function(config) {
  /**
   * Find the "oneOf" rule in the list of default rules created by react-scripts so that
   * we can add the graphql-persisted-document-loader to the list.
   */
  const oneOfRuleIndex = config.module.rules.findIndex(
    (rule) => rule.oneOf !== undefined && Array.isArray(rule.oneOf)
  );

  /**
   * Rule wasn't found - exit with an error message that lets us know what is in the list
   * of rules...
   */
  if (oneOfRuleIndex === -1) {
    throw new Error(
      `Cannot find the main build oneOf rule, rules: ${JSON.stringify(
        config.module.rules,
        stringifyConfig,
        2
      )}`
    );
  }

  /**
   * Found the oneOf rule, add the new loader to the beginning of it.
   */
  config.module.rules[oneOfRuleIndex].splice(0,0,{
    test: /\.graphql$/,
    use: [
      { loader: 'graphql-persisted-document-loader' }, // <= Before graphql-tag/loader!
      { loader: 'graphql-tag/loader' }
    ]
  });

  return config;
}
```
If the above fails to find a rule with a 'oneOf' condition, it'll stop building react and print out what rules were in the config (including their regexp tests). If it does find it properly (and it should unless you're using a custom version of react-scripts) it will add a new rule to the beginning of the list of oneOf rules that tests for a file with the 'graphql' extension.

Note: the last rule in the oneOf rules is a catch-all file-loader rule that would also match files with a 'graphql' extension. This is why the above is not simply pushing the new rule to the oneOf array - if we did, the catch-all would be used instead of the new rule. Adding it to the beginning of the array won't affect anything for javascript/css/etc, but will ensure that the new rule is used for graphql files rather than the existing catch-all file-loader rule.
