### ISSUE TITLE
i want configure the CDN in config

### ISSUE THREAD

**Issue by ZSH-HSZ** [timarney/react-app-rewired#313]

**Comment by ZSH-HSZ** [comment]
I used the js-xlsx library in the create-react-app, but it was so large that I looked through the document but couldn't find anything about the CDN

**Comment by wenjayliu** [comment]
Also looking for

**Comment by wenjayliu** [comment]
no find `externals`

**Comment by dawnmist** [comment]
I'm actually not sure what exactly you're asking for...there's not enough detail on what the issue/requirement is for me to be able to give a proper answer.

If you're asking how to compile the react app so that it can use a CDN for its url, try looking at the PUBLIC_URL environment variable documented in [create-react-app's Advanced Configuration](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#advanced-configuration).

Otherwise, please describe what you are trying to do in more detail so that we can provide better help.

**Comment by ZSH-HSZ** [comment]
I want to use js-xls cdn, https://cdn.bootcss.com/xlsx/0.12.13/xlsx.min.js, but I don't know how to configure it in config-overrides.js

**Comment by ZSH-HSZ** [comment]
My English is not good, my needs are a bit unclear, sorry.

**Comment by dawnmist** [comment]
I think I understand better now.

You'll probably want to add the [html-webpack-include-assets-plugin](https://github.com/jharris4/html-webpack-include-assets-plugin) so that the cdn script tag is automatically added to your html file during the build before the compiled bundle.js script tag, and then use :
```javascript
const HtmlWebpackIncludeAssetsPlugin = require('html-webpack-include-assets-plugin');

module.exports = function(config) {
  config.externals = {
    xlsx: 'xlsx'
  };

  config.plugins.push(
    new HtmlWebpackIncludeAssetsPlugin({
      assets: [
        'https://cdn.bootcss.com/xlsx/0.12.13/shim.min.js',
        'https://cdn.bootcss.com/xlsx/0.12.13/xlsx.min.js'
      ],
      append: false,
      publicPath: false
    })
  );

  return config;
}
```

Then in your react code, simply use `import XLSX from 'xlsx'` in the same way as if the library was being bundled.

**Comment by ZSH-HSZ** [comment]
oh, thank you, this method is feasible

**Comment by ZSH-HSZ** [comment]
the operation failed , I need to tryvvvvvvvvvvv

**Comment by ZSH-HSZ** [comment]
config.externals = {
    XLSX: 'xlsx'
  };

That's true, thank you

**Comment by ZSH-HSZ** [comment]
config.externals = {
xlsx: 'XLSX'
};

I wrote it backwards...
