### ISSUE TITLE
[BUG] react-scripts v2 does not support npm i react-app-rewired --save-dev

### ISSUE THREAD

**Issue by kopax** [timarney/react-app-rewired#333]
I am doing in a new CRA app:

    npm install react-app-rewired --save-dev

I have:

    npm WARN react-app-rewired@1.6.2 requires a peer of react-scripts@^1.0.14 but none is installed. You must install peer dependencies yourself.

**Comment by alvisyoung** [comment]
hi, could you share how you fix this issue? thanks a lot

**Comment by kopax** [comment]
Sorry I am not sure because I don't remember. I think I did a mistake in my own installation and that's why the error was poping up.

**Comment by dawnmist** [comment]
1. It is a warning, not an error. If you have _a_ version of react-scripts installed (or are using the --scripts-version to set the scripts to a different package like `react-scripts-ts`) it will still work.
2. It is because a new cra project uses react-scripts 2.x, which does not satisfy an npm peer dependency for >= 1.0.14 but < 2.0.0.
3. react-app-rewired is _not_ being updated to cra 2.x. You can read about why in the 2.0 Discussion thread. The core functionality in react-app-rewired works for cra 2.x, but many of the existing rewires were written for a previous version of Webpack, are no longer maintained by their authors, and _do not_ work correctly with cra 2.x.

**Comment by alvisyoung** [comment]
> @alvisyoung
> 
> 1. It is a warning, not an error. If you have _a_ version of react-scripts installed (or are using the --scripts-version to set the scripts to a different package like `react-scripts-ts`) it will still work despite the warning.
> 2. It is because a new cra project uses react-scripts 2.x, which does not satisfy an npm peer dependency for >= 1.0.14 but < 2.0.0.
> 3. react-app-rewired is _not_ being updated to cra 2.x. You can read about why in the 2.0 Discussion thread. The core functionality in react-app-rewired works for cra 2.x, but many of the existing rewires were written for a previous version of Webpack, are no longer maintained by their authors, and _do not_ work correctly with cra 2.x.

@dawnmist 
I think my problem is I have no react-scripts installed, could you guide me how to install it? thanks

**Comment by dawnmist** [comment]
@alvisyoung If you used create-react-app to create your project, CRA will have added react-scripts (or a version of it depending on how you ran the create-react-app function) to your project automatically.

You can check if it is missing by reading the `dependencies` section of your project's `package.json` file - it should already be listed in that section. `yarn add react-scripts` or `npm install react-scripts` will install it if it is missing.

This warning message _shouldn't_ be doing anything other than _warning_ you that the peer dependency is not being met exactly. You should still be able to use `yarn start`/`yarn build` without issues. If this is not the case, your _actual_ issue is likely to be something different.
