### ISSUE TITLE
Change React-app-rewired to create-react-app

### ISSUE THREAD

**Issue by mlusca** [timarney/react-app-rewired#372]
I'm having a problem, which on my Linux server on AWS is not running the npm build, and on my local windows is.
But this does not happen with the create-react-app project, would like to go back to the default, can you do it?
Besides the unit test does not work

**Comment by dawnmist** [comment]
All you have to do is change the start, build and test scripts back to using "react-scripts" instead of "react-app-rewired".

```json
"scripts": {
  "start": "react-scripts start",
  "test": "react-scripts test --env=jsdom",
  "build": "react-scripts build",
  ...
}
```
Just be aware that any changes you were applying inside your `config-overrides.js` will no longer be applied, as create-react-app does not use that file.

Oh, and if you're using CRA 2, you don't need the `--env=jsdom` anymore - jsdom became the default environment used for jest testing.
