### ISSUE TITLE
How to overwrite webpack.optimization?

### ISSUE THREAD

**Issue by samuelcastro** [timarney/react-app-rewired#376]
Is there a way to overwrite `webpack.optimization`? 

I'm having this problem when I attempt to change it:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'optmization'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           optmization: ...
         }
       })
     ]
```

https://webpack.js.org/configuration/optimization/

**Comment by timarney** [comment]
Closing this

Sorry - we can't offer support for webpack config questions.  Only bugs etc...

**Comment by samuelcastro** [comment]
@timarney What do you mean?  That's not a question about webpack, it's about `react-app-rewired` not overwriting `webpack.optimization` accordingly.

**Comment by dawnmist** [comment]
@samuelcastro You hadn't given any information on what you actually did, just that webpack claimed an error. The optimization config is new in Webpack V4 - I'd suggest to verify that you are actually using Webpack 4 (e.g. I know react-scripts-ts still uses Webpack V3, and you hadn't mentioned _anything_ about your setup).

The error message you posted is not itself coming from react-app-rewired, it's coming in from Webpack itself as far as I can see - i.e. Webpack is rejecting your modified config as invalid, and is reporting the list of valid keys you could use, which does not include the optimization one. That's why I'm suggesting to check that you're not trying to use options that were new in Webpack 4 with Webpack 3 by mistake.

Hence it's not a react-app-rewired bug, but a problem in your config-overrides.js file.
