### ISSUE TITLE
I have a problem with the build

### ISSUE THREAD

**Issue by jsnavarroc** [timarney/react-app-rewired#378]
I need to place the build in a different file but this is causing this problem:

> ENOENT: no such file or directory, open 'D:\React\Data\updateFrontEnd\prueba\build\2-ccdf85a272b151ebd001.js'
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The configuration is this:

**config-overrides.js**
```
   const path = require("path");
   module.exports = {
    webpack: (config, env) => {
      config.output = {
        path: path.resolve(__dirname, "dist", "sub-build"),
        filename: "[name]-[chunkhash].js",
        chunkFilename: "[name]-[chunkhash].js",
        publicPath: ""
      }
      return config;
    }
  }

```
**package.json**
```
 "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired  build",
    "test": "react-app-rewired  test --coverage",
  }

```

**Comment by dawnmist** [comment]
You'll need to patch react-scripts in order to do this, as the destination directory is also used/required in places other than the webpack config.

`react-scripts/config/paths.js`:
https://github.com/facebook/create-react-app/blob/fb6851d651311056d167f80db315312d7f5b6128/packages/react-scripts/config/paths.js#L80
https://github.com/facebook/create-react-app/blob/fb6851d651311056d167f80db315312d7f5b6128/packages/react-scripts/config/paths.js#L102
https://github.com/facebook/create-react-app/blob/fb6851d651311056d167f80db315312d7f5b6128/packages/react-scripts/config/paths.js#L136

Those paths are used by react-scripts when it creates the webpack configs (which means that once you've patched the react-scripts paths file, you shouldn't need to make changes to the webpack config to set the paths). 

My suggestion is to use a module called [patch-package](https://github.com/ds300/patch-package#readme) to create a patch for react-scripts that is reapplied every time react-scripts is reinstalled so that you don't have to create your own fork of react-scripts to change this one path.

When it comes to copying files out of the `public` directory, `react-scripts` bypasses Webpack entirely (except for the index.html file) - see: https://github.com/facebook/create-react-app/blob/4734d4ef21b165273cf722c3b11b9443f635fb44/packages/react-scripts/scripts/build.js#L190-195 
That means that even if you did fully change the location of the build folder within the webpack config, you'll still not have the files from the `public` directory being transferred properly. By patching the `react-scripts/config/paths.js` file so that it sets the paths to what you want, all the places where the build directory is being used will update to the new location properly. (Note: I use this method myself, as we have some api interface packages created by CMake and the CMake build system uses the `build` directory too - so I know that patching the paths.js file does work).
