### ISSUE TITLE
Builds fail in CI

### ISSUE THREAD

**Issue by pasali** [timarney/react-app-rewired#391]
We are using CircleCI as CI service and builds keep fails with below exception.
react-app-rewird version= 2.1.3.

    ERROR] internal/child_process.js:358
    ERROR]     throw errnoException(err, 'spawn');
    ERROR]     ^
    ERROR]
    ERROR] Error: spawn ENOMEM
    ERROR]     at ChildProcess.spawn (internal/child_process.js:358:11)
    ERROR]     at spawn (child_process.js:533:9)
    ERROR]     at Object.fork (child_process.js:108:10)
    ERROR]     at fork (/root/cockpit/cockpit-react-client/node_modules/worker-farm/lib/fork.js:17:36)
    ERROR]     at Farm.startChild (/root/cockpit/cockpit-react-client/node_modules/worker-farm/lib/farm.js:106:16)
    ERROR]     at Farm.processQueue (/root/cockpit/cockpit-react-client/node_modules/worker-farm/lib/farm.js:279:10)
    ERROR]     at Farm.<anonymous> (/root/cockpit/cockpit-react-client/node_modules/worker-farm/lib/farm.js:97:21)
    ERROR]     at ontimeout (timers.js:436:11)
    ERROR]     at tryOnTimeout (timers.js:300:5)
    ERROR]     at listOnTimeout (timers.js:263:5)
    ERROR]     at Timer.processTimers (timers.js:223:10)
    ERROR] npm ERR! code ELIFECYCLE
    ERROR] npm ERR! errno 1
    ERROR] npm ERR! cockpit@0.1.0 build: `react-app-rewired build`
    ERROR] npm ERR! Exit status 1
    ERROR] npm ERR!
    ERROR] npm ERR! Failed at the cockpit@0.1.0 build script.
    ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    ERROR]
    ERROR] npm ERR! A complete log of this run can be found in:
    ERROR] npm ERR!     /root/.npm/_logs/2019-05-03T07_02_45_427Z-debug.log

**Comment by dawnmist** [comment]
This doesn't look like a `react-app-rewired` issue.

The `ENOMEM` (Error, No Memory) looks like you're hitting the default node.js memory limit (about 1.7Gb) which is then killing the build. Likely Node.js issue: https://github.com/nodejs/node/issues/25382

Try setting the create-react-app build option ` --max-old-space-size=8192` to raise the node.js memory limit to 8Gb during build/start/test. i.e.
```json
{
  "scripts": {
    "build": "react-app-rewired --max-old-space-size=8192 build",
    "start": "react-app-rewired --max-old-space-size=8192 start",
    "test": "react-app-rewired --max-old-space-size=8192 test"
  }
}
```
If that fixes the issue, you'll need to continue to use an increased memory limit for your build. If not, you'll likely need to go through the `worker-farm` and node.js issues in order to find a work-around/bugfix. As `react-app-rewired` and `react-scripts` (the build scripts from `create-react-app`) do not themselves add the `worker-farm` library, its use is due to your project's customized build. We won't be able to help further with debugging this without an example repository that demonstrates the issue to be tested.

**Comment by pasali** [comment]
@dawnmist thank for your answer. We have found the problem and working on it to fix. So i am closing this issue since there is no relation with react-app-rewired.

**Comment by jordyvandomselaar** [comment]
@pasali Hi, what did you do to fix this? We're running into is as well.

**Comment by pasali** [comment]
@jordyvandomselaar the problem was about Terser parallelism. You can disable it either setting 
`__IS_WSL_TEST__: "true"` or you can do it in javascript like 
```
const terseDisableParallel = () => config => {
  config.optimization.minimizer[0].parallel=false;
  return config;
};
```

**Comment by jordyvandomselaar** [comment]
Awesome, thank you for the reply!
