### ISSUE TITLE
Paths option does not work on any version of react-scripts (1, 2, or 3)

### ISSUE THREAD

**Issue by jpangelle** [timarney/react-app-rewired#392]
Here is my `config-overrides.js`:

```js
const path = require('path');
module.exports = {
  paths: function(paths) {
    const { appPath } = paths;
    return {
      ...paths,
      appBuild: path.join(appPath, 'dist'),
    };
  },
};
```

**Goal:** To get the build to output to `/dist` and not `/build`.

**Issue:** During the `yarn build` command, the `dist` folder is created with `favicon.ico` and `manifest.json`, but then the `build` folder is created anyway with everything else (`static`, `index.html`, etc.) and the `build` command gives an error of: `ENOENT: no such file or directory, open '/Users/john.doe/Documents/test/dist/static/css/main.2cce8147.chunk.css'`, and that is because that file is in `build`, not `dist` where it is supposed to be.

I was originally trying this on `react-scripts v3.0.1`, so then I tried on `2.1.x` then `2.0.x`, then `1.x.x`. Same issue on all of these.

If I eject and change `appBuild`  in `paths.js` to `appBuild: resolveApp('dist')`, it works as intended so I know that I am trying to change the right path.

Am I implementing this incorrectly? Thank you.

**Comment by dawnmist** [comment]
No, the problem is that create-react-app use the build path in custom scripts _outside_ of webpack, so it is not possible to simply change the build path in the webpack config. What needs to be changed is the react-scripts's `config/paths.js` file itself.

This means that react-app-rewired is not able to do this particular job.

However, you can achieve what you want to do using an npm library called `patch-package`, as documented here: https://github.com/timarney/react-app-rewired/issues/201#issuecomment-488573268
