### ISSUE TITLE
Using react-app-rewired in express

### ISSUE THREAD

**Issue by wingland** [timarney/react-app-rewired#397]
How can I integrate react-app-rewired start in express?

**Comment by dawnmist** [comment]
If you're serving a website through express, it should be already built shouldn't it (so it has all the production optimizations/etc)? In order to do so, you'd use `react-app-rewired build` first, then get express to serve the build directory's files (no react-app-rewired required anymore at that point as the project is already compiled).

Why did you want to use the non-optimised development build through express?

**Comment by wingland** [comment]
I want to serve a dev server through express by providing some mock APIs, but I do not want to start two processes and configure the proxy, I know for webpack, there is webpack dev middleware, I wonder if there is such a solution if using react-app-rewired.

**Comment by dawnmist** [comment]
Ah - I've just been reading the create-react-app docs, and there is a way to get access to the express service that they set up by default - see: https://facebook.github.io/create-react-app/docs/proxying-api-requests-in-development#configuring-the-proxy-manually

This should also work within react-app-rewired, as react-app-rewired acts as a wrapper around the standard create-react-app react-scripts start/test/build scripts that lets you inject additional configuration settings, but then passes back to react-scripts to actually do the work of starting the build server.

Where the setupProxy.js file exports a function that takes `app` as a parameter, that app parameter is the express app. They're only showing adding proxy information to the app - but I can't see a reason why you couldn't add specific routes/handling/etc to the app at the same time.
