### ISSUE TITLE
Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by hamid07ss** [timarney/react-app-rewired#401]
Hi

i have a old project with this packages:
```json
    "react-app-rewired": "^1.5.0",
    "react-scripts": "^1.1.4",
    "react": "^16.3.1",
```

no after trying to install packages and start or build project, i got `Cannot read property 'emit' of undefined` without any details.

then i try running with `react-scripts start` and it worked!

**Comment by dawnmist** [comment]
There's not enough detail provided to be able to debug the issue - are you able to share an example repo that demonstrates the problem?

The error message you're getting is very much a _generic_ javascript error. One of the libs being used when running with react-app-rewired is trying to access an `emit` property on an undefined variable (e.g. the function signature changed to need a new parameter in one version of the library, and another library using that function hasn't been updated to provide the new parameter).

This sort of error can be caused by things like mismatched versions of other libraries such as jest & babel-jest, webpack & webpack plugins, etc (it's not usually coming from react-app-rewired itself). In these cases, the reason it usually works with react-scripts is that react-scripts will be using its own version of the affected library, and your config/installation using react-app-rewired is trying to run with a different (usually newer) version of that library resulting in the generic error you're receiving.

**Comment by hamid07ss** [comment]
I don't have time, so I can't create and share example repo
this is full log:

```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/home/sarani/Git/Workspace/omc-react/node_modules/.bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.9.2
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle project@1.2.2~prestart: project@1.2.2
6 info lifecycle project@1.2.2~start: project@1.2.2
7 verbose lifecycle project@1.2.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle project@1.2.2~start: PATH: /home/sarani/Git/Workspace/omc-react/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/sarani/Git/Workspace/omc-react/node_modules/.bin:/home/sarani/Git/Workspace/omc-react/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle project@1.2.2~start: CWD: /home/sarani/Git/Workspace/omc-react
10 silly lifecycle project@1.2.2~start: Args: [ '-c', 'react-app-rewired start' ]
11 silly lifecycle project@1.2.2~start: Returned: code: 1  signal: null
12 info lifecycle project@1.2.2~start: Failed to exec start script
13 verbose stack Error: project@1.2.2 start: `react-app-rewired start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/sarani/Git/Workspace/omc-react/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/sarani/Git/Workspace/omc-react/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid project@1.2.2
15 verbose cwd /home/sarani/Git/Workspace/omc-react
16 verbose Linux 4.15.0-54-generic
17 verbose argv "/usr/local/bin/node" "/home/sarani/Git/Workspace/omc-react/node_modules/.bin/npm" "start"
18 verbose node v10.16.0
19 verbose npm  v6.9.2
20 error code ELIFECYCLE
21 error errno 1
22 error project@1.2.2 start: `react-app-rewired start`
22 error Exit status 1
23 error Failed at the project@1.2.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by dawnmist** [comment]
The log still doesn't say _anything_ about where the attempt to access the `emit` field of an undefined variable occurs, just that you'd tried to run `react-app-rewired start` and it returned an error.

**Comment by hamid07ss** [comment]
this is a really bad error! there is no more details!!!!!

when i install `react-app-rewired` and `react-scripts` globally and run with `sudo` it's works fine!
and my global package versions is latest for both, but if i install latest version in project, it's not working!!!

**Comment by timarney** [comment]
What does you config-overrides.js file look like.  You likely have an issue there not this package.

**Comment by hamid07ss** [comment]
@timarney I already checked.
But now I checked again, and the problem is not this file.

but [Here](https://github.com/timarney/react-app-rewired/issues/401#issuecomment-508359977) I say that on using sudo and global package, it's works  fine!!!

**Comment by dawnmist** [comment]
1. you should not need to use sudo with node_modules, _ever_, and
2. if it is running with a global install and not a local install, it points to you having something inside your node_modules directory that is causing this (that the global installs are not seeing/invoking).

It again comes back to the question of _what other packages_ are you using, and _how_ are you including them?

React-app-rewired does not contain the word `emit` inside its code base. It is _not_ react-app-rewired itself that is throwing the error - it _never_ tries to access an `emit` variable. The error is coming from another module inside your `node_modules` directory.

The only thing I can suggest you do is to look at what packages are installed in `node_modules/react-scripts/node_modules`, and compare the version of those to any packages with the same name in your `node_modules` directory - it is most likely that you have an updated version of a package inside `node_modules` that is not compatible with the standard modules that `react_scripts` uses. When run with `react_scripts`, the version of the package in `node_modules/react-scripts/node_modules` is used, and when run with `react-app-rewired` the version of the package in `node_modules` is used instead and either itself tries to access another package by a different api, or is providing a different api that is being misused.

Without an example repo, or your `package.json` file + `config-overrides.js`, there is nothing further we can do. Your problem is not due to `react-app-rewired` itself - it's due to something in your `package.json` file not being compatible with the normal packages used by `react-scripts`.

**Comment by hamid07ss** [comment]
the problem is `react-app-rewire-antd-theme` that used in `config-overrides.js`

but still i can't fix the issue :-/ and i don't know why this project on another pc that installed 4 month ago working correctly!!!!!

so, thanks.
