### ISSUE TITLE
Dotenv not working with react-app-rewired v1.x

### ISSUE THREAD

**Issue by finaxar-arthur** [timarney/react-app-rewired#407]
I have `"react-app-rewired": "1.4.0"` and I am trying to use the `dotenv` package to get my environment variables.

However, when doing `yarn build`, I always get this issue

```
yarn run v1.17.3
$ react-app-rewired --max_old_space_size=8192 build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/dotenv/lib/main.js:28 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

I have consulted `dotenv` docs and some related issue but nothing solved the problem.

Anyone knows how I can solve this?

**Comment by dawnmist** [comment]
* What version of create-react-app are you using? If it's CRA 2.x or later, you need to use react-app-rewired 2.x (because the version of webpack used changed in CRA 2.0, requiring a lot of plugin changes/etc).
* What version of dotenv are you using?
* Are you directly importing dotenv into your react app (i.e. do you have the code `import dotenv from 'dotenv'` anywhere)? If so, you shouldn't be - create-react-app directly passes any variables beginning with "REACT_APP" to your application _without_ needing to import the dotenv library yourself. See https://github.com/motdotla/dotenv/issues/261#issuecomment-398266309
