### ISSUE TITLE
Running relay tests

### ISSUE THREAD

**Issue by sepans** [timarney/react-app-rewired#410]
I have a relay app that was created with CRA and it is working just fine with the [config-overrides](https://github.com/sepans/ctzen/blob/9c18d5428b904514a004f0602074ab3b347950f7/config-overrides.js):

```js
module.exports = override(
  addBabelPlugins(
    "relay",
  ),
);
```

But when running tests I get the error:

`Invariant Violation: graphql: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as 'graphql'`

which should be an indication that the relay babel plugin is not loaded. I read through https://github.com/timarney/react-app-rewired/issues/240 and https://github.com/timarney/react-app-rewired/issues/241 and as I understood it those overrides are not applied to jest test settings but I am a bit confused how exactly it needs to be setup (sorry the great tools you developed made me lazy and never learned those settings in depth ❤️ ).

A will greatly appreciate your help figuring this out.

Thank you.

PS: the code I am working on is [here](https://github.com/sepans/ctzen/pull/19)

**Comment by dawnmist** [comment]
Thank you for the repo link - it was very helpful, because it meant I could test what I was about to suggest.

React-app-rewired turns on processing of your `.babelrc` or `babel` section of your `package.json` file when running tests.

Try adding the following to your `package.json` file (note that it is limiting the configuration to being used in the test environment):
```json
  "babel": {
    "env": {
      "test": {
        "plugins": [
          "relay"
        ]
      }
    }
  }
```
After adding that bit, your tests ran but complained about having the wrong password/wrong number of assertions. The graphql error you quoted is gone, so I believe that the relay plugin is being used properly.

**Comment by sepans** [comment]
Thank you very much for you quick response. It worked. I guess that is equivalent of adding
```json
{
  "env": {
    "test": {
      "plugins": [
        "relay"
      ]
    }
  }
}
```

in the `.babelrc` file. Thank you I can take it from here and will post a link to the working test here just for the reference.
