### ISSUE TITLE
README treats examples as black magic.

### ISSUE THREAD

**Issue by przemo-hemmersbach** [timarney/react-app-rewired#419]
There are two examples given, one is module exporting a fuction one is module exporting an object (neither example specifies why, or if those are alternative or some edge cases).
Secondly neither one of them explains what are arguments of them or where can information on the shape if it be found.

This readme unnecessarily assumes that an user already is familiar with settings and configurations. But whole point of this package is to break out of defaults - most people will recongize they have to gain knowledge in this area just before npm -i react-app-rewired

Please add some more links to relevant docs if not fuller explanaitions.

**Comment by dawnmist** [comment]
Can I suggest you take a little bit more time to reread the documentation before you complain about it missing parts that are actually covered in some depth.

[Why this project exists](https://github.com/timarney/react-app-rewired#why-this-project-exists)

Introduction statement:
> Tweak the create-react-app webpack config(s) without using 'eject' and without creating a fork of the react-scripts.

From the [Extended Configuration](https://github.com/timarney/react-app-rewired#extended-configuration-options) Section:
> **By default, the config-overrides.js file exports a single function to use when customising the webpack configuration** for compiling your react app in development or production mode. **It is possible to instead export an object from this file** that contains up to three fields, each of which is a function. This **alternative** form allows you to also customise the configuration used for Jest (in testing), and for the Webpack Dev Server itself.

Admittedly: that paragraph needs updating a little for the new `paths` field (subsection 4 in the Extended Configuration section) as there are now 4 optional fields instead of 3, but that field _is_ documented inside it's own subsection of the Extended Configuration section. This bit just got missed when the documentation was updated for the new field.

The entire Extended Configuration section _is_ documentation on the object form, and the first subsection within it specifies that the `webpack` field of the object form is to provide the exact same function as you would use if using the single-function-only form and provides further documentation on that function.

The section regarding Jest (for test configuration) contains links to both the Jest documentation and the Babel configuration documentation. It also discusses alternative ways to configure both of these as it's likely that most configuration changes for jest/babel can be done through the package.json file instead of specifying a function to modify the jest configuration. It also documents the config parameter for this function.

The Webpack Dev Server section documents the devServer field, and fully documents what the function parameters are and what the return value needs to be in order to modify the configuration used by CRA for the Webpack Dev Server that gets run when you use `npm start` or `yarn start`.

The only external documentation not directly linked to is the Webpack documentation itself - and yes, it is assumed that you've already looked that up because otherwise you would have no need to look at react-app-rewired at all. Making changes to your webpack configuration without having already looked at the webpack documentation yourself is asking for problems.

About the only bit that I don't see documented is the original function's `env` parameter, which is either 'production' for `yarn build`/`npm build` or 'development' (or missing) for `yarn start`/`npm build`.

Any improvements to documentation via pull request would be very welcome.
