### ISSUE TITLE
How to support yarn2？

### ISSUE THREAD

**Issue by vvni** [timarney/react-app-rewired#423]
![image](https://user-images.githubusercontent.com/50414099/69013591-a7169c80-09bc-11ea-974e-537afb863448.png)

**Comment by dawnmist** [comment]
Why would yarn 2 reject the path `/Users/vvni/OffSource/yunmeng-mall-webapp/config-overrides.js`? Are you sure that you haven't made a typo in the `config-overrides.js` filename (i.e. that the problem is simply that yarn isn't finding the file)?

**Comment by vvni** [comment]
I am sure there is no problem with the configuration, you can give it a try.ღ( ´･ᴗ･` ）
在 2019年11月18日 +0800 AM8:29，Janeene Beeforth <notifications@github.com>，写道：

**Comment by dawnmist** [comment]
As far as I can see, yarn 2 is not yet released (even as an alpha). If the `config-overrides.js` file is present, but yarn 2 is rejecting that file as not found, wouldn't that be an error in yarn itself and need to be reported there?

**Comment by vvni** [comment]
But using react-scripts does not cause this problem！
在 2019年11月18日 +0800 AM8:54，timarney/react-app-rewired <reply@reply.github.com>，写道：
>
> As far as I can see, yarn 2 is not yet released (even as an alpha). If the config-overrides.js file is present, but yarn 2 is rejecting that file as not found, wouldn't that be an error in yarn itself and need to be reported there?

**Comment by dawnmist** [comment]
React-scripts doesn't try to use your config-overrides.js file, so of course you won't get yarn complaining it cannot find that file.

I'm sorry - without access to your project, I cannot help any further. My own repos are using typescript which yarn 2 explicitly mentions requires new pnp stuff to even use, so testing on those introduces additional issues that are likely not present in your project. The error message yarn is giving is that it cannot _find_ the config-overrides.js file, and it lists the set of filepaths it tried. I still believe you have an accidental typo in your filename, as that's the only _valid_ reason I can see for why yarn wouldn't find it. Otherwise it'd be a bug in yarn itself (and a fairly serious one), and not anything to do with react-app-rewired, as yarn _is_ looking for the correct file when you are using react-app-rewired.

Can you show a screenshot of the files in your project's base directory?

**Comment by vvni** [comment]
Sorry, this is my problem. The cause of the problem is as you said.
