### ISSUE TITLE
Convert Webpack.optimization to react-app-rewired

### ISSUE THREAD

**Issue by itcvmaster** [timarney/react-app-rewired#424]
I am trying to use react-app-rewired, but faced some difficulties for optimization.

`
module.exports = {
  //...
  optimization: {
    splitChunks: {
      chunks: 'all'
      name: false
    }
  }
};
`

How can I do it in react-app-revwired?

**Comment by dawnmist** [comment]
What version of create-react-app are you using?

CRA already includes the `optimization: { splitChunks: { chunks: 'all', name: false} }` setting: https://github.com/facebook/create-react-app/blob/4604c5e52c4fbac5c450ac0e58382775e24f3220/packages/react-scripts/config/webpack.config.js#L277-L280

Otherwise, you'd add it to the config like:
```
module.exports = (config) => {
   config.optimization.splitChunks = { chunks: 'all', name: false };
   return config;
}
```
which would replace any pre-existing definition for splitChunks, or add it if there is no definition. Being safe, you may want to verify that the optimization field already exists, and add it first if it didn't:
```
module.exports = (config) => {
   if (!config.optimization) {
     config.optimization = {};
   }
   config.optimization.splitChunks = { chunks: 'all', name: false };
   return config;
}
```

But as I said - it's already part of react-scripts from create-react-app (I think it got added as part of the 2.0 release), so you may want to check your `node_modules/react-scripts/config/webpack.config.js` file - if it's in there, you don't need to use react-app-rewired for this.
