### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by Brhernann** [timarney/react-app-rewired#425]
Hi, im using "react-app-rewired build" with "react-create-app" and after in the browser i have this error:

> Uncaught SyntaxError: Unexpected token '<'

can be my config-overrides.js ? 

   `
         const { override, fixBabelImports, addLessLoader } = require('customize-cra')
     module.exports = override(
       fixBabelImports('import', {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
    }),
    addLessLoader({
        javascriptEnabled: true,
        modifyVars: {
            '@menu-dark-bg':' rgb(9, 90, 165)', // background sidebar (replacing dark theme)
            '@layout-sider-background':'rgb(9, 90, 165)', // background sidebar (space no use)
            '@layout-trigger-background':'rgb(9, 90, 165)', //footer sidebar
        },
    })
)
`

**Comment by with-heart** [comment]
I created a project with the same config and installed `antd`, `babel-plugin-import`, and `less-loader` and it runs fine. 

What versions of `react-app-rewired` and `customize-cra` are you using?

**Comment by Brhernann** [comment]
"react-app-rewired": "^2.1.3",
  "customize-cra": "^0.8.0",
 "less-loader": "^5.0.0",

are you using webpack config?

**Comment by with-heart** [comment]
Huh, installed the same versions and not having any issues. I'm using the same `config-overrides.js` you have for webpack config. Could you reproduce on codesandbox.io?

**Comment by dawnmist** [comment]
Usually when I've seen that error in the browser, it means that I've received the `index.html` file instead of the javascript file that was requested. Check in the Devtools Network tab in your browser for the particular files that are reporting that error - there's usually a Preview option under there that will show you the contents of the response that your browser received.

Are you using the service worker at all? I ask because that was the cause of why I would get that error occurring at times - the browser was given the old manifest/filename list and was trying to retrieve the _old_ versions of files that it hadn't cached, but because the files had been recompiled and had new hashes the old versions didn't exist anymore. Most react projects are set up to send the index.html page for all paths that do not map to a file on disk, so the browser was receiving the index.html page when the service worker caused the browser to request the old javascript filenames.

**Comment by Brhernann** [comment]
> Huh, installed the same versions and not having any issues. I'm using the same `config-overrides.js` you have for webpack config. Could you reproduce on codesandbox.io?

i haven't webpack config friend, it can be it?

**Comment by Brhernann** [comment]
> Usually when I've seen that error in the browser, it means that I've received the `index.html` file instead of the javascript file that was requested. Check in the Devtools Network tab in your browser for the particular files that are reporting that error - there's usually a Preview option under there that will show you the contents of the response that your browser received.
> 
> Are you using the service worker at all? I ask because that was the cause of why I would get that error occurring at times (immediately after deploying a new version) - the browser was given the old manifest/filename list and was trying to retrieve the _old_ versions of files that it hadn't cached, but because the files had been recompiled and had new hashes the old versions didn't exist anymore. Most react projects are set up to send the index.html page for all paths that do not map to a file on disk, so the browser was receiving the index.html page when the service worker caused the browser to request the old javascript filenames.

![image](https://user-images.githubusercontent.com/18491638/69348852-9c2a6900-0c55-11ea-8c04-70a26b33f90b.png)

**Comment by twobear** [comment]
I think you overwrit it's build path .maybe you can wirting like this:

```
const path = require('path');
const config = require('./config');
const wconfig = require('./webpack'); //your wpack config

function merge(target,source){
    Object.assign(target,source)
}

const pathsConfig = require('react-scripts/config/paths');//react-scripts paths
// devserver port
process.env.PORT=config.DEV_SERVER_PORT;
module.exports = function override(defaultConfig, env) {
// i just need modiffy production
    if(env==='production'){
        // 修改打包目录
        merge(pathsConfig,
            {
                appBuild:path.join(path.dirname(pathsConfig.appBuild), config.uri.pub)
            });
        merge(defaultConfig,wconfig);
    }
    return defaultConfig;
};
 
```

**Comment by dawnmist** [comment]
@Brhernann That's exactly what I was describing.

You currently have the "Console" tab open in devtools. To the right of it is the "Network" tab.
1. Click on the "Network" tab.
2. Click on the `main.*.chunk.js` file on the left side.
3. Click on the "Preview" tab.
![image](https://user-images.githubusercontent.com/5810277/69400431-c5c2bd80-0d45-11ea-90e7-ec682880981a.png)

In the Preview tab, do you see your index.html page, or javascript content? I _believe_ you will be seeing your index.html page instead of the javascript that should be in your javascript file.

If you see the index.html file content instead of javascript, there are 2 things I know of that can cause it:
* Creating a PWA app as per https://create-react-app.dev/docs/making-a-progressive-web-app - I have seen the service worker cause the browser to try to download files that have since been deleted from the server when the site has just been built again, OR
* Your _web server_ configuration has an error, so that it is returning the index.html file instead of the javascript files it is supposed to be returning.

Neither of those are related to react-app-rewired or your config-overrides.js file.

**Comment by Brhernann** [comment]
> @Brhernann That's exactly what I was describing.
> 
> You currently have the "Console" tab open in devtools. To the right of it is the "Network" tab.
> 
> 1. Click on the "Network" tab.
> 2. Click on the `main.*.chunk.js` filename on the left side.
> 3. Click on the "Preview" tab.
>    ![image](https://user-images.githubusercontent.com/5810277/69400431-c5c2bd80-0d45-11ea-90e7-ec682880981a.png)
> 
> In the Preview tab, do you see your index.html page, or javascript content? I _believe_ you will be seeing your index.html page instead of the javascript that should be in your javascript file.
> 
> If you see the index.html file content instead of javascript, there are 2 things I know of that can cause it:
> 
> * Creating a PWA app as per https://create-react-app.dev/docs/making-a-progressive-web-app - I have seen the service worker cause the browser to try to download files that have since been deleted from the server when the site has just been built again, OR
> * Your _web server_ configuration has an error, so that it is returning the index.html file instead of the javascript files it is supposed to be returning.
> 
> Neither of those are related to react-app-rewired or your config-overrides.js file.

yes, sorry Neither of those are related to react-app-rewired or your config-overrides.js file.

the problem was the web server configuration, thanks

**Comment by adi-BW** [comment]
Hey...I am having same issue.
Can you please tell how you solved the problem?

**Comment by camillalo** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
