### ISSUE TITLE
Consider using --save instead of --save-dev in README

### ISSUE THREAD

**Issue by websocket98765** [timarney/react-app-rewired#428]
This is relevant because builds on Netlify fail when `react-app-rewired` is in `devDependencies` property of package.json, with the error "Cannot find react-app-rewired" that occurs when it tries to run the build command. Moving `react-app-rewired` it into the `dependencies` property solved this. (`react-scripts` is also in `dependencies`, not `devDependencies`, by default.)

**Comment by dawnmist** [comment]
1. Usually `yarn build` is considered a development command - there's many other packages that are needed for a build that are not typically required in order to run the site after it has been compiled. This includes things like babel, linters, compilers for scss => css, webpack and plugins, typescript type definitions for libraries, jest or other testing frameworks, etc.

2. According to [Netlify's documentation](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-environment), unless you _change_ the default environment from 'development' to 'production' Netlify should install the devDependencies.

Production environment is supposed to be only the packages required in order for the site itself (after compiling) to be able to run - i.e. libraries like React, Redux, etc. By that point in time, you should already have a pre-compiled site and no longer have any requirement for react-app-rewired.

By all means use --save instead of --save-dev yourself if your environment is set up such that you _have_ to have react-app-rewired as a runtime dependency instead of a development dependency. Just be aware that this is _not_ the normal/common way in which build-time-only dependencies are specified, and hence (at least in my opinion) changing the documentation in this case isn't really appropriate.

**Comment by websocket98765** [comment]
Update for Googlers:
1. I wanted to keep NODE_ENV=production in my Netlify env vars, in case anything being built behaved differently for production env.
2. I moved all `dependencies` into `devDependencies`, to be semantically correct based on the above post, given it's a static site and deps are only needed during the build.
3. I added `--dev` to my install/build command on Netlify: `npm ci --dev && npm run build` so both devDependencies and dependencies are installed.

Dawn was correct with this [link](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-environment). Alternatively, I could remove my NODE_ENV and let Netlify default it to 'development' and use `npm ci && npm run build` (untested), though I feel better using NODE_ENV=production for my production bulids.
