### ISSUE TITLE
Support "type": "module"

### ISSUE THREAD

**Issue by dimaqq** [timarney/react-app-rewired#431]
I wanted to enable `"type": "module"` in package.json in my project.
(some silly reason, like writing own helper scripts as ES modules, whatever)

However, it seems I can't use `react-app-rewired` in this case, node (v13.3.0) tells me that:

```
> yarn start
yarn run v1.21.0
$ react-app-rewired start
(node:5530) Warning: require() of ES modules is not supported.
require() of myproj/config-overrides.js from myproj/node_modules/react-app-rewired/config-overrides.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename myproj/config-overrides.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from myproj/package.json.
```

I can't rename my local `config-overrides` to `cjs` extension as that's not found by `react-app-rewired`. I seems that rewired hardcodes the name of the override file.

I wonder, if, perhaps, rewired can be updated to be an ES module so that it can import all kinds of modules/packages/etc?
Or would that break other things?

**Comment by dawnmist** [comment]
React-app-rewired actually uses standard node.js name resolution, in that it imports `path/to/config-overrides` and not `path/to/config-overrides.js`.

This means that it can also be a directory containing an index.js (that can itself require other files), or a directory containing a package.json with a `main` field pointing to any filename. See https://www.freecodecamp.org/news/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8/ for a discussion of how name resolution in node works & what it actually looks for.

Can you test if the following sorts out your issue:
* Create a `config-overrides` directory
THEN EITHER
* Move your existing `config-overrides.js` file to `config-overrides/index.js`
* Create a file `config-overrides/package.json` file with the name of the directory & version.
* Set the `type` field in the `config-overrides/package.json` to either `commonjs` or leave the type field out altogether.
OR
* Move your existing `config-overrides.js` file to `config-overrides/index.cjs`
* Create a file `config-overrides/package.json` file with the name of the directory & version.
* Set the `main` field in the `config-overrides/package.json` to `./index.cjs`

This should make the config-overrides be processed using commonjs syntax without affecting the rest of your project.

**Comment by dimaqq** [comment]
Thanks, I'll try it out tomorrow 😄

**Comment by dimaqq** [comment]
That works, thanks for work arounds and the doc link :)

As far as I understand, config overrides just cannot be an ES module though, right?

**Comment by dawnmist** [comment]
As to it not being able to be an ES module - I've never tried, so I'm not sure. ES modules use different syntax for including other files (e.g. `import` instead of `require` - hence the error messages you were getting initially) so you'd need to modify the syntax used in the file to match the module format. It is being run through node.js, and I don't remember node.js as supporting `import` syntax directly. That wouldn't be a problem if the file was being compiled _prior_ to being run by node.js instead of being run directly, but you would then need to create that compile step as an additional step yourself and make sure that `./config-overrides` resolved to the compiled version of the file.

So I believe that by default it does need to be a commonjs module type for node.js to be able to use the file directly, though it's potentially possible to use ES Modules if you were to create an additional compile step to convert that ES Module into commonjs format prior to using it in the react-app-rewired build process.

**Comment by Tarunmeena0901** [comment]
@dawnmist is it possible that I can movve the config-override directory in some other directory inside root directory for example
./scripts/config-override   .  will it still work or may can I make it work ?

**Comment by camillalo** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
