### ISSUE TITLE
ie 11 'webpackHotUpdate' is undefined

### ISSUE THREAD

**Issue by aselcuk** [timarney/react-app-rewired#445]
my typescript based project is working on chrome but ie 11 and edge browsers has errors.

package.json

`"@types/node": "^12.12.24"`
`"@types/react": "^16.9.17"`
`"@types/react-dom": "^16.9.4"`
`"react": "^16.12.0"`
`"react-app-polyfill": "^1.0.6"`
`"react-dom": "^16.12.0"`
`"react-scripts": "3.3.0"`

errors

![p](https://user-images.githubusercontent.com/41209531/75807074-d5ff2580-5d95-11ea-9d8b-fe00a1a91ddc.PNG)

**Comment by dawnmist** [comment]
This is completely unrelated to react-app-rewired. It is part of create-react-app itself.

Please refer to the [supported browsers information](https://create-react-app.dev/docs/supported-browsers-features) for create-react-app. IE and Edge are not supported in development mode by default, and IE 11 requires polyfills to be added for production mode in order to work.
