### ISSUE TITLE
Less Loader has been initialized using an options object that does not match the API schema.

### ISSUE THREAD

**Issue by junhwong** [timarney/react-app-rewired#458]
this is my override script:
```js
const { override, fixBabelImports, addLessLoader, addBabelPlugins } = require('customize-cra');
module.exports = override(
    fixBabelImports('import', {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true, // 'css'
    }),
    addBabelPlugins(
        [
            '@babel/plugin-proposal-decorators',
            { legacy: true }
        ]
    ),
    addLessLoader(),
);
```
Failed to compile.

./node_modules/antd/es/style/index.less (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--6-oneOf-7-3!./node_modules/antd/es/style/index.less)
ValidationError: Invalid options object. Less Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'source'. These properties are valid:
   object { lessOptions?, prependData?, appendData?, sourceMap?, implementation? }

**Comment by dawnmist** [comment]
I think the "source" option is being added by [this line](https://github.com/arackaf/customize-cra/blob/89690d738ffed10d2d7d8c236798c97959615df3/src/customizers/webpack.js#L168) in the addLessLoader override function.

Since that is part of the customize-cra project rather than part of react-app-rewired, you'll need to ask further from the team at customize-cra. They'll be better able to help than we will, since they wrote the code in question.
