### ISSUE TITLE
Trying to force dev environment to output files to the build directory

### ISSUE THREAD

**Issue by tylerssn** [timarney/react-app-rewired#471]
I'm hoping to dump my output to the build directory even in development mode. I have confirmed that `yarn start` is applying my `config-overrides.js` but none of my files are being dumped to the build directory.

Any advice would be greatly appreciated.

```js
const path = require('path')

module.exports = function override(config, env) {
  config.devServer = { ...config.devServer, writeToDisk: true };
  config.output = { ...config.output, path: path.join(__dirname, 'build') }
  return config;
}
```

**Comment by dawnmist** [comment]
Create-react-app's config file created/updated in the standard override _does not_ get used for configuring the webpack dev server. They use a separate config for the dev server, so any changes made to the normal one do not get applied.

As documented in the readme, you need to use the alternative format in order to be able to specify webpack dev server configuration overrides.

```js
const path = require('path')

module.exports = {
  webpack: function override(config, env) {
    // Overrides to build here...
    // Though I think this path is set by default, so no override for it should be needed...
    config.output = { ...config.output, path: path.join(__dirname, 'build') };
    return config;
  },
  devServer: function(configFunction) {
    return function(proxy, allowedHost) {
      // Create the default config by calling configFunction with the proxy/allowedHost parameters
      const config = configFunction(proxy, allowedHost);

      // Changes to devServer here.
      config.devServer = {...config.devServer, writeToDisk: true };
      return config;
    }    
  }
};
```

Edit: My apologies - I thought I'd submitted this comment a few days ago.

**Comment by tylerssn** [comment]
Thanks much for taking the time to provide this. I'll compare this with what I stitched together [over here](https://github.com/improper/react-browser-extension). I was able to output the files but found that some from `public` weren't included in the devServer write and therefore had to be manually copied.
