### ISSUE TITLE
Problem with install react-app-rewired with React Typescript Project

### ISSUE THREAD

**Issue by LinkedForest** [timarney/react-app-rewired#478]

**Comment by dawnmist** [comment]
I use react-app-rewired with a react typescript project. What problem are you experiencing?

Without a description of the problem, there is nothing we can do to help you.

**Comment by LinkedForest** [comment]
yarn run v1.22.4
$ react-app-rewired start --scripts-version react-scripts-ts
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'react-scripts-ts/package.json'

**Comment by LinkedForest** [comment]
package.js

{
  "name": "swiftr",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "react": "^16.13.1",
    "react-app-rewired": "^2.1.6",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "typescript": "~3.7.2"
  },
  "scripts": {
    "start": "react-app-rewired start --scripts-version react-scripts-ts",
    "build": "react-app-rewired build --scripts-version react-scripts-ts",
    "test": "react-app-rewired test --scripts-version react-scripts-ts",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by dawnmist** [comment]
You don't have react-scripts-ts installed. New versions of create-react-app support typescript natively, so you do not need the `--scripts-version react-scripts-ts` anymore. The only time the `--scripts-version` option is needed is when you are _not_ using the standard react-scripts package.

**Comment by LinkedForest** [comment]
yarn run v1.22.4
$ react-app-rewired start
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'D:\Linked_Project\Swiftr\src\react-app-env.d.ts'

**Comment by dawnmist** [comment]
That's indicating that you haven't set up the project as a typescript project with create-react-app properly, as that file should be installed by create-react-app during the creation of the project. It's a typescript compilation error because a typescript type definition file that is required is missing (and not anything to do with react-app-rewired).

What command did you use to create the project? Is this a new project, or are you migrating an existing project from javascript to typescript?

The instructions for creating a typescript project with create-react-app are [here](https://create-react-app.dev/docs/adding-typescript).
