### ISSUE TITLE
I have issue on install react-app-rewired with React Typescript

### ISSUE THREAD

**Issue by LinkedForest** [timarney/react-app-rewired#479]
I Create App with this code:
yarn create react-app my-app --template typescript

I Used This in Package.json

{
  "name": "swiftr",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@jpavon/react-scripts-ts": "^1.2.2",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "react": "^16.13.1",
    "react-app-rewired": "^2.1.6",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "typescript": "~3.7.2"
  },
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

And This is the issue:

yarn run v1.22.4
$ react-app-rewired start
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'D:\Linked_Project\Swiftr\src\react-app-env.d.ts'

**Comment by dawnmist** [comment]
Please don't open multiple bug reports for the same issue. I was still responding to you on #478.

If you run `yarn react-scripts start` (i.e. excluding react-app-rewired), you will get the _same_ error message.

The problem is that the `src/react-app-env.d.ts` file that is supposed to have been created by create-react-app during the initialization of the project is missing from your project's src directory. That has absolutely nothing at all to do with react-app-rewired.

That file is included by react-scripts here: https://github.com/facebook/create-react-app/blob/8e720aefc62586346396f9e3c257288e1562888b/packages/react-scripts/config/paths.js#L103

Can I suggest you first get the project actually compiling with react-scripts, _then_ add react-app-rewired.

**Comment by dawnmist** [comment]
Please create the file `src/react-app-env.d.ts` with the contents:
```js
/// <reference types="react-scripts" />

```

Reading the create-react-app source code, that seems to be what that file was supposed to contain. See: https://github.com/facebook/create-react-app/blob/c87ab79559e98a5dae2cd0b02477c38ff6113e6a/packages/react-scripts/scripts/utils/verifyTypeScriptSetup.js#L263-L268
