### ISSUE TITLE
Adding custom tsonfig.json path

### ISSUE THREAD

**Issue by BadMask121** [timarney/react-app-rewired#482]
Is there a way to set a custom path for the tsconfig e.g it would be best to set config file when building `react-app-rewired build -p tsconfig.build.json`

**Comment by dawnmist** [comment]
I think you can use the `paths` option to set the tsconfig file name to use. The tsconfig file name is set in the `paths.appTsConfig` variable [here](https://github.com/facebook/create-react-app/blob/97695bc960a839ce6f390b0aeb1591e0e4410573/packages/react-scripts/config/paths.js#L92)

Try something like:
```js
module.export = {
  webpack: (config, env) => {
    // ...edit your webpack config
    return config;
  },
  paths: (paths, env) => {
    if (process.env.NODE_ENV === 'production') {
      paths.appTsConfig = 'tsconfig.build.json';
    }
    return paths;
  }
}
```
You _might_ need to also set the directory for where to find that file rather than only the file name.
