### ISSUE TITLE
configuration.optimization.splitChunks.cacheGroups['vendor'].test should be an instance of...

### ISSUE THREAD

**Issue by PatNeedham** [timarney/react-app-rewired#485]
```
$create-react-app --version
3.4.1
```
These are my devDependencies:
```
  "devDependencies": {
    "react-app-rewired": "^2.1.6",
    "react-scripts": "^3.4.3",
    "webpack-merge": "^5.1.2"
  }
```
My `config-overrides.js` looks like this:
```
const { merge } = require('webpack-merge');
// import originalConfig from 'react-scripts/config/webpack.config';

module.exports = function override(config, env) {
  //do stuff with the webpack config...
  return merge(config, {
    optimization: {
      runtimeChunk: 'single',
      splitChunks: {
        automaticNameDelimiter: '~',
        automaticNameMaxLength: 100,
        chunks: 'all',
        maxInitialRequests: Infinity,
        minSize: 0,
        cacheGroups: {
          vendor: {
            test: /[\\/]node_modules[\\/]/,
            name(module) {
              // get the name. E.g. node_modules/packageName/not/this/part.js
              // or node_modules/packageName
              const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];
  
              // npm package names are URL-safe, but some servers don't like @ symbols
              return `npm.${packageName.replace('@', '')}`;
            },
          },
        },
      },
    },
  });
}

```
After changing the build script to `react-app-rewired build`, running `build` results in:
```
Creating an optimized production build...
Failed to compile.

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.optimization.splitChunks should be one of these:
   false | object { automaticNameDelimiter?, automaticNameMaxLength?, cacheGroups?, chunks?, fallbackCacheGroup?, filename?, hidePathInfo?, maxAsyncRequests?, maxInitialRequests?, maxSize?, minChunks?, minSize?, name? }
   -> Optimize duplication and caching by splitting chunks by shared modules and cache group
   Details:
    * configuration.optimization.splitChunks.cacheGroups['vendor'].test should be an instance of function
    * configuration.optimization.splitChunks.cacheGroups['vendor'].test should be a string.
    * configuration.optimization.splitChunks.cacheGroups['vendor'].test should be an instance of RegExp
    * configuration.optimization.splitChunks.cacheGroups['vendor'].test should be one of these:
      function | string | RegExp
      -> Assign modules to a cache group
```
The strange part is, when I copy that `optimization` object directly into the `react-scripts` [webpack.config.js](https://github.com/facebook/create-react-app/blob/v3.4.1/packages/react-scripts/config/webpack.config.js#L206-L283) (replacing what currently exists there), I do not encounter this issue.

Does anyone have an idea what might be causing this?

**Comment by dawnmist** [comment]
I've just tried to duplicate what you're seeing by creating a new react-app project using the default install plus your specified `devDependencies` and your `config-overrides.js`. The project built successfully (using Linux - Debian 10 'Buster' and node 10.22.0).

What OS are you using?
What version of node.js are you using?

The error message is explicitly complaining about the regexp for the `cacheGroups['vendor'].test`. It's looking like your regexp is attempting to handle either Windows or Unix paths - but if so you may be missing a `\` in the path separator characters for the regexp (and later in the `packageName = module.context.match` regexp too), causing the system to think that the regexp is ending inside the `[]` character test. What happens if you change the test to:
```js
cacheGroups: {
  vendor: {
    test: /[\\\/]node_modules[\\\/]/,
    name(module) {
      const packageName = module.context.match(/[\\\/]node_modules[\\\/](.*?)([\\\/]|$)/)[1];
      return `npm.${packageName.replace('@', '')}`;
    },
  },
},
```

**Comment by dawnmist** [comment]
You may also need to adjust the packageName match for Windows using `\\` as a path separator instead of just `\` - at present the match is only looking for a single character between the node_modules and next portion of the path, so:
```js
    name(module) {
      const packageName = module.context.match(/[\\\/]node_modules[\\\/]+(.*?)([\\\/]|$)/)[1];
      return `npm.${packageName.replace('@', '')}`;
    },
```
(Based on information from https://github.com/webpack/webpack/issues/2073 - while older, the discussion on path matching is still relevant).

**Comment by PatNeedham** [comment]
I'm using macOS 10.15.6, and my version of node is 12.13.0

After switching the cacheGroups field to the suggestion above, I still see the same console error. And eslint doesn't like the triple backslashes
![image](https://user-images.githubusercontent.com/967811/91724025-a83f4180-eb6a-11ea-8868-7a95d5f3d6a6.png)

**Comment by dawnmist** [comment]
Ok on eslint, sorry that didn't help at all.

I've finally got hold of a Mac where I could test this, and the same set of steps that I took on the linux machine are resulting in the build working correctly with your config-overrides.js file on the Mac.

I'm starting to suspect that the issue may be being misreported a little by webpack, e.g. if the function fails to run properly/throws an error for some reason with a particular package name, it's resulting in the webpack compiler believing that the function itself is invalid.

You _should_ be able to get further information by adding logging messages to your function that lets you know what module (if any) the build got up to before the build fails, and what the result of your packageName match was:
```js
name(module) {
  console.log(`Processing module: ${module.context}`);
  const packageName = module.context.match(/[\\/]node_modules[\\/]+(.*?)([\\/]|$)/)[1];
  console.log(`    packageName=${packageName}`);
  return `npm.${packageName.replace('@', '')}`;
}
```
This will at least let you know if the function is being called at any point because it'll log the file path for the module being called. If there are _any_ "Processing module: ..." logs, the last one reported before the build fails would be the one likely causing issues with the build. If there are no module logs, the issue would be occurring prior to that function being called for the first time which would eliminate the possibility that it was being caused by a package name not being processed properly. The packageName log will let you check that you're getting the expected matches from the regexp for those names (if there are indeed some modules being processed).
