### ISSUE TITLE
SecurityError: the operation is insecure

### ISSUE THREAD

**Issue by akougblenou** [timarney/react-app-rewired#489]
Hi I recently tried to access my app which is rewired on Safari and couldn't access it.
I got a message that said "SecurityError: The operation is insecure".

The issue and its solution is highlighted [here](https://stackoverflow.com/questions/59359280/react-app-error-failed-to-construct-websocket-an-insecure-websocket-connecti), only it is not in react-app-rewired but in create react-app.

The issue has been fixed on that package since then, my question is : is there a way to bring this fix into react-app-rewired ?

**Comment by dawnmist** [comment]
React-app-rewired uses the same scripts as you have installed for react-scripts - it simply wraps around them so that you can modify the config given to them. The way to fix this should simply be for you to update the version of react-scripts used in your project to the version that pulls in the bugfix. i.e. This is entirely owned by the original CRA part of the build system.
