### ISSUE TITLE
Issue: File system api when used inside webworker gives packaging issue with no error message

### ISSUE THREAD

**Issue by rjvijesh** [timarney/react-app-rewired#503]
I have to read the files from the local machine and trying to write into the files from web-worker.js and have taken reference from this link https://www.html5rocks.com/en/tutorials/file/filesystem-sync/

web-worker.js

    self.requestFileSystemSync = self.webkitRequestFileSystemSync || self.requestFileSystemSync;
    console.log("requestFileSystemSync", requestFileSystemSync);
    
    var fs = requestFileSystemSync(TEMPORARY, 1024 * 1024 /*1MB*/);
    postMessage('Got file system.');
    
    var fileEntry = fs.root.getFile("demo.txt", {create: false});
    
    var writer = fileEntry.createWriter();
    writer.seek(writer.length);
    writeDataToLogFile(writer);

I am packaging my react app using react-app-wired module and serving it locally and getting the following error for error click here [error screenshot][1].
Without the filesystem api mentioned in webworker, my app works completely fine (ie) gets packaged properly, builds & runs successfully fine local machine using same command. my local custom config looks like below:

*config.module.rules.push({
        test: /\.worker\.js$/,
        use: {
            loader: 'worker-loader',
            options: {
                inline: 'fallback'
            }
        }
    })*

![webworker_error](https://user-images.githubusercontent.com/41643804/98548529-a2c74b80-22bf-11eb-90bc-a202dda8af22.png)

**Comment by dawnmist** [comment]
We've seen issues with webworkers previously as a result of how react-scripts lints and reports on errors (stuff react-app-rewired doesn't actually have any control over). When webworkers do not compile, the entire package fails to be written out to the build directory.

Two things to check:
1. If you are using `self` in the webworker, you need to tell eslint to not reject it. Add the comment  `// eslint-disable-next-line no-restricted-globals` to the line before any use of `self`, or alternatively at the top of the file turn that off for the whole file with `/* eslint no-restricted-globals: 0 */`
2. An error in the webworker file can cause the compilation to fail while react-scripts still reports to the console that it succeeded. The incorrect log message about the build succeeding in this case comes from react-scripts happens because react-scripts does not know that there is a second set of entry files (for the webworker) included in the Webpack config and therefore doesn't retrieve/show their errors.

You can check if there is an issue with the eslint linting on the webworker files (because react-scripts won't report them!) by using the command `npx eslint ./PATH_TO_YOUR_WORKER_FILE -c ./node_modules/eslint-config-react-app/index.js` as written in the comment: https://github.com/timarney/react-app-rewired/issues/362#issuecomment-520770592

If neither of those possibilities helps, are you able to share a sample repository that has the issue so I can dig in to debug further?

**Comment by rjvijesh** [comment]
checked with above possibility, but it is not working

**Comment by dawnmist** [comment]
Are you able to share a sample repository that has the issue so I can dig in to debug further?

**Comment by rjvijesh** [comment]
the issue got fixed
by adding both the lines below
 /* eslint no-restricted-globals: 0 */

// eslint-disable-next-line no-restricted-globals
