### ISSUE TITLE
File sizes after gzip ： no such file or directory

### ISSUE THREAD

**Issue by chenfeng** [timarney/react-app-rewired#616]
no such file or directory。
when I use react-app-rewired to compile my project the terminal shows 'File sizes after gzip: ENOENT: no such file or directory, ...'.
This is my config-overrides.js
```js
const path = require('path')
module.exports = {
  webpack: function (config, env) {
    //do stuff with the webpack config...
    config.output.path = path.join(__dirname, '../server/static')
    return config
  },
}
```

**Comment by dawnmist** [comment]
Create-react-app does some of its actions on the path outside of webpack, which means that modifying the output path in webpack doesn't actually modify all the places where the output path is used.

Version 5 of CRA allows you to set an environment variable `BUILD_PATH` to specify the output path - which means that you wouldn't need react-app-rewired _if_ that was the only modification you needed.

If you are using an older version of CRA, you will need to use the `paths` option instead of the `webpack` option to modify the output path:

```js
const path = require('path');

module.exports = {
  paths: function(paths, env) {
    paths.appBuild = path.join(__dirname, '../server/static');
    return paths;
}
```
You can refer to the react-scripts paths config for the path names: https://github.com/facebook/create-react-app/blob/main/packages/react-scripts/config/paths.js
