### ISSUE TITLE
hardcoded NODE_ENV production?

### ISSUE THREAD

**Issue by JonathanAsbury-Dovaxis** [timarney/react-app-rewired#655]
Why are you forcing production on NODE_ENV in scripts/build.js
During a development build, it causes all process.env values to exclusively load production values.

**Comment by dawnmist** [comment]
For a development build, you should be using the start script, not the build script.

Create-react-app also enforces NODE_ENV=build when building the app. This means you'll still have production variables enforced by create-react-app's react-scripts anyway, and is why react-app-rewired does the same thing.

From [Create-react-app's documentation](https://create-react-app.dev/docs/adding-custom-environment-variables):
> There is also a built-in environment variable called **NODE_ENV**. You can read it from process.env.NODE_ENV. When you run npm start, it is always equal to 'development', when you run npm test it is always equal to 'test', and when you run npm run build to make a production bundle, it is always equal to 'production'. **You cannot override NODE_ENV manually**. This prevents developers from accidentally deploying a slow development build to production.

You can override these variables by:
- using `.env.production.local` to have the local version used for builds on your own machine, if production builds are always created in CI rather than locally, or
- using [dotenvx](https://github.com/motdotla/dotenv#dotenvx) to specify an environment file to load into the shell, and then passing that through to the build script, e.g. ` dotenvx --env-file=.env.development -- yarn build` when wanting to create a development build instead of using the start scripts to have access to reloading/etc of development builds.

Sorry for the delay in response - Github has apparently stopped notifying me of new issues being created. 😞

**Comment by JonathanAsbury-Dovaxis** [comment]
Thanks for the feedback.  .env.production.local is a viable option for us.  We currently have to build a version that get's pushed to our dev environment.  Both .env.production.local and dotenvx look like solid options.  Thanks for suggesting them!
I really appreciate the follow-up!
