### ISSUE TITLE
Create tests for the supported react-scripts version

### ISSUE THREAD

**Issue by pasviegas** [timarney/react-app-rewired#9]
I think we can create tests reading the config and asserting if the right values are there for each rewire. This way when react-script upgrades we can be sure that our code still works.

I can do this. hehe

**Comment by timarney** [comment]
Absolutely makes sense to setup tests for the rewires.

**Comment by timarney** [comment]
Now that lerna is up and running what are your thoughts on setting the tests?  

Should we setup an example app inside each of the packages to test against?

**Comment by timarney** [comment]
Or maybe something like this would be easier to maintain https://github.com/insin/nwb/blob/master/tests/createWebpackConfig-test.js

**Comment by timarney** [comment]
@pasviegas just FYI - I built out a quick integration test here for the Preact Rewire (mostly because I wanted to play around to https://www.cypress.io/).  https://github.com/timarney/preact-rewire-test .

Also just noting at some point - I'll see about patching up the Jest Config to see if I can get that working for quick Smoke Tests.

**Comment by timarney** [comment]
@pasviegas if you have time at some point I started a branch to get this testing setup https://github.com/timarney/react-app-rewired/tree/config-tests.

What are your thoughts on the best way to pull in the Webpack config?

**Comment by timarney** [comment]
Closing this for now.  I have integration tests setup for some primary cases.  Will re-open this as needed.
